/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as IndexRouteImport } from './routes/index';
import { Route as PublicPrivacyPolicyIndexRouteImport } from './routes/_public/privacy-policy/index';
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index';
import { Route as PublicAppAuthIndexRouteImport } from './routes/_public/app-auth/index';
import { Route as PrivateAccessUserIndexRouteImport } from './routes/_private/access-user/index';
import { Route as PrivateNewUserTokenRouteImport } from './routes/_private/new-user/$token';
import { Route as PublicAppAuthResetPasswordTokenRouteImport } from './routes/_public/app-auth/reset-password/$token';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicPrivacyPolicyIndexRoute =
  PublicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => PublicRoute,
  } as any);
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAppAuthIndexRoute = PublicAppAuthIndexRouteImport.update({
  id: '/app-auth/',
  path: '/app-auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateAccessUserIndexRoute = PrivateAccessUserIndexRouteImport.update({
  id: '/access-user/',
  path: '/access-user/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateNewUserTokenRoute = PrivateNewUserTokenRouteImport.update({
  id: '/new-user/$token',
  path: '/new-user/$token',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicAppAuthResetPasswordTokenRoute =
  PublicAppAuthResetPasswordTokenRouteImport.update({
    id: '/app-auth/reset-password/$token',
    path: '/app-auth/reset-password/$token',
    getParentRoute: () => PublicRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/new-user/$token': typeof PrivateNewUserTokenRoute;
  '/access-user/': typeof PrivateAccessUserIndexRoute;
  '/app-auth/': typeof PublicAppAuthIndexRoute;
  '/contact/': typeof PublicContactIndexRoute;
  '/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/new-user/$token': typeof PrivateNewUserTokenRoute;
  '/access-user': typeof PrivateAccessUserIndexRoute;
  '/app-auth': typeof PublicAppAuthIndexRoute;
  '/contact': typeof PublicContactIndexRoute;
  '/privacy-policy': typeof PublicPrivacyPolicyIndexRoute;
  '/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/new-user/$token': typeof PrivateNewUserTokenRoute;
  '/_private/access-user/': typeof PrivateAccessUserIndexRoute;
  '/_public/app-auth/': typeof PublicAppAuthIndexRoute;
  '/_public/contact/': typeof PublicContactIndexRoute;
  '/_public/privacy-policy/': typeof PublicPrivacyPolicyIndexRoute;
  '/_public/app-auth/reset-password/$token': typeof PublicAppAuthResetPasswordTokenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/new-user/$token'
    | '/access-user/'
    | '/app-auth/'
    | '/contact/'
    | '/privacy-policy/'
    | '/app-auth/reset-password/$token';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/new-user/$token'
    | '/access-user'
    | '/app-auth'
    | '/contact'
    | '/privacy-policy'
    | '/app-auth/reset-password/$token';
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/new-user/$token'
    | '/_private/access-user/'
    | '/_public/app-auth/'
    | '/_public/contact/'
    | '/_public/privacy-policy/'
    | '/_public/app-auth/reset-password/$token';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/privacy-policy/': {
      id: '/_public/privacy-policy/';
      path: '/privacy-policy';
      fullPath: '/privacy-policy/';
      preLoaderRoute: typeof PublicPrivacyPolicyIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/contact/': {
      id: '/_public/contact/';
      path: '/contact';
      fullPath: '/contact/';
      preLoaderRoute: typeof PublicContactIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/app-auth/': {
      id: '/_public/app-auth/';
      path: '/app-auth';
      fullPath: '/app-auth/';
      preLoaderRoute: typeof PublicAppAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/access-user/': {
      id: '/_private/access-user/';
      path: '/access-user';
      fullPath: '/access-user/';
      preLoaderRoute: typeof PrivateAccessUserIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/new-user/$token': {
      id: '/_private/new-user/$token';
      path: '/new-user/$token';
      fullPath: '/new-user/$token';
      preLoaderRoute: typeof PrivateNewUserTokenRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/app-auth/reset-password/$token': {
      id: '/_public/app-auth/reset-password/$token';
      path: '/app-auth/reset-password/$token';
      fullPath: '/app-auth/reset-password/$token';
      preLoaderRoute: typeof PublicAppAuthResetPasswordTokenRouteImport;
      parentRoute: typeof PublicRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateNewUserTokenRoute: typeof PrivateNewUserTokenRoute;
  PrivateAccessUserIndexRoute: typeof PrivateAccessUserIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateNewUserTokenRoute: PrivateNewUserTokenRoute,
  PrivateAccessUserIndexRoute: PrivateAccessUserIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicAppAuthIndexRoute: typeof PublicAppAuthIndexRoute;
  PublicContactIndexRoute: typeof PublicContactIndexRoute;
  PublicPrivacyPolicyIndexRoute: typeof PublicPrivacyPolicyIndexRoute;
  PublicAppAuthResetPasswordTokenRoute: typeof PublicAppAuthResetPasswordTokenRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAppAuthIndexRoute: PublicAppAuthIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicPrivacyPolicyIndexRoute: PublicPrivacyPolicyIndexRoute,
  PublicAppAuthResetPasswordTokenRoute: PublicAppAuthResetPasswordTokenRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
